" Plugins
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin('~/.vim/plugged')
Plug 'vim-airline/vim-airline'
call plug#end()

let g:airline_powerline_fonts = 0
let g:airline_symbols_ascii = 1

let g:airline_section_x = ''
let g:airline_section_y = ''
let g:airline_section_z = '%l/%L, %v'
let g:airline_section_error = ''
let g:airline_section_warning = ''

" Backspace
set backspace=indent,eol,start

" Blanks
set list listchars=tab:»\ ,trail:·

" Compatibility
set nocompatible

" Highlight
if has("syntax")
  syntax on
endif

if has("autocmd")
  if v:version > 701
    autocmd Syntax * call matchadd('Debug', '\W\zs\(DEBUG\)')
    autocmd Syntax * call matchadd('Error', '\W\zs\(ERROR\|FATAL\)')
  endif
endif

" Interface
set laststatus=2
set number
set showcmd
set noshowmode
set title

" Line Break
set linebreak

" Paste
set pastetoggle=<F2>

" Search
set hlsearch
set ignorecase
set incsearch
set nowrapscan
set smartcase

" Key Mappings
nmap <C-h> <C-W>h
nmap <C-j> <C-W>j
nmap <C-k> <C-W>k
nmap <C-l> <C-W>l

imap jk <Esc>
