" Plugins
if empty(glob('~/.vim/autoload/plug.vim'))
  silent! curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin('~/.vim/plugged')
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
call plug#end()

let g:airline_theme = 'deus'

let g:airline_powerline_fonts = 0
let g:airline_symbols_ascii = 1

let g:airline_section_x = ''
let g:airline_section_y = ''
let g:airline_section_z = '%l/%L, %v'
let g:airline_section_error = ''
let g:airline_section_warning = ''

" Backspace
set backspace=indent,eol,start

" Blanks
set list listchars=tab:»\ ,trail:·

" Color
if &term =~ "256color"
  set background=dark
  if has("termguicolors")
    let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
    let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"
    set termguicolors
  endif
endif

" Cursor
autocmd BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif

" Compatibility
set nocompatible

" Highlight
if has("syntax")
  syntax on
endif

autocmd Syntax * call matchadd('Debug', '\W\zs\(DEBUG\)')
autocmd Syntax * call matchadd('Error', '\W\zs\(ERROR\|FATAL\)')

" Interface
set laststatus=2
set relativenumber
set showcmd
set noshowmode
set title
set wildmenu
set wildmode=longest,full

" Line Break
set linebreak

" Paste
set pastetoggle=<F2>

" Search
set hlsearch
set ignorecase
set incsearch
set nowrapscan
set smartcase

" Split
set splitright
set splitbelow

" Swap
if empty(glob($HOME . "/.vim/swap"))
  call mkdir($HOME . "/.vim/swap", "p")
  set directory=$HOME/.vim/swap
elseif isdirectory($HOME . "/.vim/swap")
  set directory=$HOME/.vim/swap
endif

" Tags
set tags=./tags,tags;

" Key Mappings
let mapleader = ","

imap jk <Esc>

nmap <Leader><Space> :nohlsearch<CR>

nmap <C-H> <C-W>h
nmap <C-J> <C-W>j
nmap <C-K> <C-W>k
nmap <C-L> <C-W>l
