set -g mouse on
set -g set-clipboard on

# space-nvim
set -g pane-active-border-style fg='#a45bad'
set -g status-style bold,bg='#a45bad'

bind e setw synchronize-panes
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
