# Oh My Zsh
export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="injae"

plugins=(
  git
  zoxide
  zsh-syntax-highlighting
)

source $ZSH/oh-my-zsh.sh

# Zsh
unsetopt hist_verify
setopt rmstarsilent
zstyle ":completion:*" insert-tab false

# Key Bindings
if [ $TERM = "xterm" ]; then
  bindkey "^[[1~" beginning-of-line
  bindkey "^[[4~" end-of-line
fi

# Bat
if [ $(uname) = "Darwin" ]; then
  export MANROFFOPT="-c" MANPAGER="sh -c 'col -bx | bat -l man -p'"
  alias bat="bat --tabs=8"
else
  case $(lsb_release -is) in
    Debian|Ubuntu)
      export MANPAGER="sh -c 'col -bx | batcat -l man -p --pager=\"less -R\"'"
      alias bat="batcat --tabs=8"
      ;;
    *)
      export MANROFFOPT="-c" MANPAGER="sh -c 'col -bx | bat -l man -p'"
      alias bat="bat --tabs=8"
  esac
fi

# Vim
alias view="vim -R"

# NeoVim
if [ $(uname) = "Darwin" ]; then
  export PATH="$PATH:/opt/nvim-macos-arm64/bin"
else
  export PATH="$PATH:/opt/nvim-linux-x86_64/bin"
fi
alias nv="nvim"

# dmesg
alias dmesg="sudo dmesg"

# OOB
function oob {
  if [ $# -ne 2 ]; then
    echo "Usage: oob <gateway> <oob_ip>"
    return 1
  fi

  local session="oob"
  local proxy="ssh -D localhost:8888 -N $1 -v"
  local chrome="/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --proxy-server=socks5://localhost:8888 https://$2"

  tmux new-session -d -s "$session"
  tmux send-keys -t "${session}:0.0" "$proxy" C-m
  tmux split-window -t "${session}:0"
  tmux send-keys -t "${session}:0.1" "$chrome" C-m
  tmux attach -t "$session"
}

# SSH
function sshloop {
  while true; do
    ssh "$@"
    if [ $? -eq 0 ]; then
      break
    fi
    sleep 2
  done
}

# SysRq
function sysrq {
  sudo sh -c "echo $1 > /proc/sysrq-trigger"
}
