# Zsh
setopt rmstarsilent

# Path to oh-my-zsh installation
export ZSH="$HOME/.oh-my-zsh"

# Shell theme
ZSH_THEME="injae"

# Plugins
plugins=(
  autojump
  git
  zsh-syntax-highlighting
)

source $ZSH/oh-my-zsh.sh

# Key bindings
if [ $TERM = "xterm" ]; then
  bindkey '^[[1~' beginning-of-line
  bindkey '^[[4~' end-of-line
fi

# User configuration

# Environment variables
export MANPAGER="sh -c 'col -bx | batcat -l man -p --pager=\"less -R\"'"

# Aliases
alias bat="batcat"
